# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            Î”P
tagline:          'Big Sibs for you kids!'
description:      'Elite group of high school students that understands the unique needs of students. For students, by students.'
url:              http://hyde.getpoole.com

author:
  name:           'Ryan Zhang'
  url:            https://twitter.com/mdo

paginate:         5

# Custom vars
version:          2.0.0

github:
  repo:           https://github.com/poole/hyde